name: monorepo

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      args:
        - VITE_BACKEND_URL=http://44.222.104.0:3000
        - VITE_CHECK=vite env check
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data: